spring:
  application:
    name: pii-detection
  datasource:
    url: jdbc:h2:file:./data/db/pii-detection
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql


app:
  name: MySpringApp
  version: 1.0.0
